---
- hosts: all
  strategy: debug
  vars_files:
    - vars/defaults.yml
  pre_tasks:
  - name: sudo apt-get update
    apt: update_cache=yes
    become: yes
    become_method: sudo
  - name: sudo apt-get install libcurl4-openssl-dev ruby-dev and nodejs dependencies  
    apt: 
      name:
        - libcurl4-openssl-dev
        - ruby-dev
        - zlib1g-dev
        - liblzma-dev
        - git-core
        - nodejs
    become: yes
    become_method: sudo
  roles:
    - { role: deployer.user,tags: deployer }
    - { role: rvm_io.ruby, tags: ruby }
    - { role: ANXS.postgresql,tags: postgresql,postgresql_version: 9.3,become: yes,become_user: root }
    - { role: geerlingguy.passenger,tags: passenger, become: yes, become_user: root }
  post_tasks:
  - name: 'Add Git repo to host'
    become: yes
    become_user: '{{ deploy_user }}'
    git: repo={{ git_repo_url }} accept_hostkey=yes clone=no update=no
  - name: 'Running Post Tasks'
    shell: echo 'Completed!'

