# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa9a3478291da2e30a92fc5cd7c6da46ac9af59d85a562eeb4640a31cabdfe3539f924092212c5ac4c46164a9258183f151264b161fa630c78923dc3fc020192

test:
  secret_key_base: b33ab6c4ff27e9ab2d85571003320b05c36a4ebce5ec1b030dfa66a8eacdf9fc6cc8114584cc8bc3820b1b73380d63703320e8e124e8df9adaa1488faa31225a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: b84aace446e5db7b068af9b227a5f3871280fa8dbbdfc7595b045567f976fcdbb490c29b0f08d08d4d9c069b7182d4da87649e388500a0bf992e65e943d3db46
